SELECT DISTINCT EMPLOYEES.eid, EMPLOYEES.ename, EMPLOYEES.salary
FROM EMPLOYEES, CERTIFIED, AIRCRAFT, SCHEDULE, FLIGHTS
WHERE EMPLOYEES.eid=CERTIFIED.eid, CERTIFIED.aid=AIRCRAFT.aid, SCHEDULE.aid=AIRCRAFT.aid, FLIGHTS.flno=SCHEDULE.flno
